export const Cards = [
  {
    id: 1,
    name: "amazon",
    img: "src/images/amazon.svg",
    isFlipped: false,
  },
  {
    id: 2,
    name: "android",
    img: "src/images/android.svg",
    isFlipped: false,
  },
  {
    id: 3,
    name: "apple",
    img: "src/images/apple.svg",
    isFlipped: false,
  },
  {
    id: 4,
    name: "behance",
    img: "src/images/blogger.svg",
    isFlipped: false,
  },
  {
    id: 5,
    name: "deviantart",
    img: "src/images/deviantart.svg",
    isFlipped: false,
  },
  {
    id: 6,
    name: "digg",
    img: "src/images/digg.svg",
    isFlipped: false,
  },
  {
    id: 7,
    name: "dribbble",
    img: "src/images/dribbble.svg",
    isFlipped: false,
  },
  {
    id: 8,
    name: "dropbox",
    img: "src/images/dropbox.svg",
    isFlipped: false,
  },
  {
    id: 9,
    name: "ebay",
    img: "src/images/ebay.svg",
    isFlipped: false,
  },
  {
    id: 10,
    name: "facebook",
    img: "src/images/facebook.svg",
    isFlipped: false,
  },
  {
    id: 11,
    name: "flickr",
    img: "src/images/flickr.svg",
    isFlipped: false,
  },
  {
    id: 12,
    name: "forrst",
    img: "src/images/forrst.svg",
    isFlipped: false,
  },
  /* 
  {
    id: 13,
    name: "gdrive",
    img: "src/images/gdrive.svg",
    isFlipped: false,
  },
  {
    id: 14,
    name: "github",
    img: "src/images/github.svg",
    isFlipped: false,
  },
  {
    id: 15,
    name: "gplus",
    img: "src/images/gplus.svg",
    isFlipped: false,
  },
  {
    id: 16,
    name: "instagram",
    img: "src/images/instagram.svg",
    isFlipped: false,
  },
  {
    id: 17,
    name: "lastfm",
    img: "src/images/lastfm.svg",
    isFlipped: false,
  },
  {
    id: 18,
    name: "linkedin",
    img: "src/images/linkedin.svg",
    isFlipped: false,
  },
  {
    id: 19,
    name: "picasa",
    img: "src/images/picasa.svg",
    isFlipped: false,
  },
  {
    id: 20,
    name: "pinterest",
    img: "src/images/pinterest.svg",
    isFlipped: false,
  },
  {
    id: 21,
    name: "reddit",
    img: "src/images/reddit.svg",
    isFlipped: false,
  },
  {
    id: 22,
    name: "rss",
    img: "src/images/rss.svg",
    isFlipped: false,
  },

  {
    id: 23,
    name: "skype",
    img: "src/images/skype.svg",
    isFlipped: false,
  },
  {
    id: 24,
    name: "soundcloud",
    img: "src/images/soundcloud.svg",
    isFlipped: false,
  },
  {
    id: 25,
    name: "stumbleupon",
    img: "src/images/stumbleupon.svg",
    isFlipped: false,
  },
  {
    id: 26,
    name: "tumblr",
    img: "src/images/tumblr.svg",
    isFlipped: false,
  },
  {
    id: 27,
    name: "twitter",
    img: "src/images/twitter.svg",
    isFlipped: false,
  },
  {
    id: 28,
    name: "vimeo",
    img: "src/images/vimeo.svg",
    isFlipped: false,
  },
  {
    id: 29,
    name: "vine",
    img: "src/images/vine.svg",
    isFlipped: false,
  },
  {
    id: 30,
    name: "windows",
    img: "src/images/windows.svg",
    isFlipped: false,
  },
  {
    id: 31,
    name: "wordpress",
    img: "src/images/wordpress.svg",
    isFlipped: false,
  },
  {
    id: 32,
    name: "yahoo",
    img: "src/images/yahoo.svg",
    isFlipped: false,
  },
  {
    id: 33,
    name: "youtube",
    img: "src/images/youtube.svg",
    isFlipped: false,
  }, */
  {
    id: 34,
    name: "amazon",
    img: "src/images/amazon.svg",
    isFlipped: false,
  },
  {
    id: 35,
    name: "android",
    img: "src/images/android.svg",
    isFlipped: false,
  },
  {
    id: 36,
    name: "apple",
    img: "src/images/apple.svg",
    isFlipped: false,
  },
  {
    id: 37,
    name: "behance",
    img: "src/images/blogger.svg",
    isFlipped: false,
  },
  {
    id: 38,
    name: "deviantart",
    img: "src/images/deviantart.svg",
    isFlipped: false,
  },
  {
    id: 39,
    name: "digg",
    img: "src/images/digg.svg",
    isFlipped: false,
  },
  {
    id: 40,
    name: "dribbble",
    img: "src/images/dribbble.svg",
    isFlipped: false,
  },
  {
    id: 41,
    name: "dropbox",
    img: "src/images/dropbox.svg",
    isFlipped: false,
  },
  {
    id: 42,
    name: "ebay",
    img: "src/images/ebay.svg",
    isFlipped: false,
  },
  {
    id: 43,
    name: "facebook",
    img: "src/images/facebook.svg",
    isFlipped: false,
  },
  {
    id: 44,
    name: "flickr",
    img: "src/images/flickr.svg",
    isFlipped: false,
  },
  {
    id: 45,
    name: "forrst",
    img: "src/images/forrst.svg",
    isFlipped: false,
  },
  /*
  {
    id: 46,
    name: "gdrive",
    img: "src/images/gdrive.svg",
    isFlipped: false,
  },
  {
    id: 47,
    name: "github",
    img: "src/images/github.svg",
    isFlipped: false,
  },
  {
    id: 48,
    name: "gplus",
    img: "src/images/gplus.svg",
    isFlipped: false,
  },
  {
    id: 49,
    name: "instagram",
    img: "src/images/instagram.svg",
    isFlipped: false,
  },
  {
    id: 50,
    name: "lastfm",
    img: "src/images/lastfm.svg",
    isFlipped: false,
  },
  {
    id: 51,
    name: "linkedin",
    img: "src/images/linkedin.svg",
    isFlipped: false,
  },
  {
    id: 52,
    name: "picasa",
    img: "src/images/picasa.svg",
    isFlipped: false,
  },
  {
    id: 53,
    name: "pinterest",
    img: "src/images/pinterest.svg",
    isFlipped: false,
  },
  {
    id: 54,
    name: "reddit",
    img: "src/images/reddit.svg",
    isFlipped: false,
  },
  {
    id: 55,
    name: "rss",
    img: "src/images/rss.svg",
    isFlipped: false,
  },

  {
    id: 56,
    name: "skype",
    img: "src/images/skype.svg",
    isFlipped: false,
  },
  {
    id: 57,
    name: "soundcloud",
    img: "src/images/soundcloud.svg",
    isFlipped: false,
  },
  {
    id: 58,
    name: "stumbleupon",
    img: "src/images/stumbleupon.svg",
    isFlipped: false,
  },
  {
    id: 59,
    name: "tumblr",
    img: "src/images/tumblr.svg",
    isFlipped: false,
  },
  {
    id: 60,
    name: "twitter",
    img: "src/images/twitter.svg",
    isFlipped: false,
  },
  {
    id: 61,
    name: "vimeo",
    img: "src/images/vimeo.svg",
    isFlipped: false,
  },
  {
    id: 62,
    name: "vine",
    img: "src/images/vine.svg",
    isFlipped: false,
  },
  {
    id: 63,
    name: "windows",
    img: "src/images/windows.svg",
    isFlipped: false,
  },
  {
    id: 64,
    name: "wordpress",
    img: "src/images/wordpress.svg",
    isFlipped: false,
  },
  {
    id: 65,
    name: "yahoo",
    img: "src/images/yahoo.svg",
    isFlipped: false,
  },
  {
    id: 66,
    name: "youtube",
    img: "src/images/youtube.svg",
    isFlipped: false,
  }, */
];
